Don't restore savedInstanceState
This possibly fixes #13

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ogsdroid/com.ogsdroid.TabbedActivity}: kotlin.KotlinNullPointerException
Caused by: kotlin.KotlinNullPointerException
at com.ogsdroid.MyGamesFragment.onCreate(MyGamesFragment.kt:50)
at android.support.v4.app.Fragment.performCreate(Fragment.java:2075)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1060)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1277)
at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2149)
at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:190)
at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:353)
at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:88)
at com.ogsdroid.TabbedActivity.onCreate(TabbedActivity.kt:182)
at android.app.Activity.performCreate(Activity.java:6912)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2900)